name: Mirror to GitVerse

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # Получаем полный репозиторий со всей историей коммитов
      - name: Checkout full repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Полностью синхронизируем репозиторий с GitVerse
      - name: Mirror to GitVerse
        env:
          # Токен доступа к GitVerse
          GITVERSE_TOKEN: ${{ secrets.GITVERSE_TOKEN }}

          # Имя пользователя или организации в GitVerse
          GITVERSE_OWNER: ${{ vars.GITVERSE_OWNER }}

        run: |
          if [ -z "$GITVERSE_TOKEN" ]; then
            echo "Ошибка: secret GITVERSE_TOKEN не задан"
            exit 1
          fi

          if [ -z "$GITVERSE_OWNER" ]; then
            echo "Ошибка: variable GITVERSE_OWNER не задан"
            exit 1
          fi

          REPO_NAME="${GITHUB_REPOSITORY#*/}"

          GITVERSE_URL="https://${GITVERSE_TOKEN}@gitverse.ru/${GITVERSE_OWNER}/${REPO_NAME}.git"

          git remote add gitverse "$GITVERSE_URL"

          git push gitverse --mirror
